# Generated by Django 2.1.1 on 2019-05-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitie', '0002_auto_20190529_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='recruitie.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='recruitie.Lead')),
            ],
        ),
    ]
