# Generated by Django 2.1.1 on 2019-05-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitie', '0003_candidatenote_leadnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadnote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
